### ISSUE TITLE
geolocationmarker-compiled.js - 404 not found 

### ISSUE THREAD

**Issue by morkov4o** [jacopotarantino/google-maps-utility-library-v3#1]
//google-maps-utility-library-v3.googlecode.com/svn/trunk/geolocationmarker/src/geolocationmarker-compiled.js

**Comment by jacopotarantino** [comment]
Sorry, I cloned this repo mostly just to make sure it didn't get deleted. I'm not maintaining it. Let me know if you find a solution!
